[package]
name = "enter_the_dreamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_ecs_ldtk = "0.8.0"
bevy_rapier2d = { version = "0.22.0" , features = ["debug-render-2d"] }
